"""
Generate targeted training data specifically engineered to elevate the 4 key evaluation pillars:
Pillar 1: Indian Finance Terms (~70% -> ~90%)
Pillar 2: SEBI / AMFI Regulatory Knowledge (~60% -> ~88%)
Pillar 3: Step-by-Step Numerical Explanations (~65% -> ~82%)
Pillar 4: Fiduciary Advisory Tone & Professional Empathy (88% -> ~93%)

All text is written in authoritative, natural, and SEBI-compliant advisory English.
"""

import argparse
import json
import math
import random
from pathlib import Path

OUT_JSONL = Path("data/raw/corpus_v2/four_pillars_mastery.jsonl")
MIB = 1024 ** 2

NAMES = [
    "Aarav", "Ananya", "Rohan", "Sneha", "Karan", "Pooja", "Vikram", "Meera",
    "Aditya", "Divya", "Suresh", "Kavita", "Arjun", "Neha", "Manish", "Priya",
    "Rahul", "Ritu", "Sanjay", "Farah", "Imran", "Nikhil", "Deepak", "Anjali"
]
CITIES = ["Bengaluru", "Mumbai", "Pune", "Hyderabad", "Delhi NCR", "Chennai", "Kolkata", "Ahmedabad"]


def money(x):
    x = round(x)
    s = str(abs(int(x)))
    if len(s) > 3:
        head, tail = s[:-3], s[-3:]
        parts = []
        while len(head) > 2:
            parts.insert(0, head[-2:]); head = head[:-2]
        if head:
            parts.insert(0, head)
        s = ",".join(parts + [tail])
    return ("-" if x < 0 else "") + s


def R(x):
    return float(round(x))


def lakh(x):
    if x >= 1e7:
        return f"about ₹{x/1e7:.2f} crore"
    if x >= 1e5:
        return f"about ₹{x/1e5:.2f} lakh"
    return f"about ₹{money(x)}"


# =========================================================================== #
# PILLAR 1: Indian Finance Terms & Market Vocabulary (Target: 90%)
# =========================================================================== #
def gen_indian_finance_terms(r):
    term = r.choice([
        "cas_statement", "cutoff_timings", "ter_regulation52", "exit_load_fifo",
        "arbitrage_cost_of_carry", "tracking_error_difference", "portfolio_turnover_ratio",
        "direct_growth_nav_spread", "stamp_duty_stt", "sid_kim_factsheet"
    ])
    
    if term == "cas_statement":
        return """Indian Financial Terms: Consolidated Account Statement (CAS)

A Consolidated Account Statement (CAS) is a single, authoritative document that aggregates all financial investments held by an investor across the entire Indian capital market landscape, linked to their Permanent Account Number (PAN).

1. Types of CAS in India:
• RTA CAS (CAMS & KFintech): Jointly generated by India's two registered Registrar and Transfer Agents (RTAs). It consolidates all mutual fund folios across all 44 Asset Management Companies (AMCs) in India where units are held in physical/statement of account (SOA) form.
• Depository CAS (NSDL & CDSL): If mutual fund units or shares are held in dematerialized (Demat) form through brokers like Zerodha, Groww, or Angel One, the central depository (NSDL or CDSL) issues a comprehensive monthly CAS combining demat equity shares, mutual funds, sovereign gold bonds (SGBs), and corporate bonds.

2. Generation Schedule & Frequency:
Under SEBI directives, a CAS is sent via email (eCAS) on or before the 15th of every month for folios that experienced any financial transaction (such as an SIP instalment, lump sum purchase, switch, or redemption) in the preceding calendar month. If no transactions occurred, a half-yearly CAS is dispatched every April and October.

3. Why CAS is Essential for Investors:
• Eliminates portfolio blind spots by discovering old, forgotten folios.
• Verifies that nominee designations, email addresses, and bank IFSC mandates are uniformly updated.
• Enables seamless import into portfolio trackers via password-protected PDFs (the password is universally the investor's uppercase PAN followed by date of birth in DDMMYYYY format)."""

    elif term == "cutoff_timings":
        return """Market Mechanics: SEBI Cut-Off Timings and Same-Day NAV Allocation

In Indian mutual fund investing, the specific time at which an investment application and corresponding funds reach the AMC determines the Net Asset Value (NAV) applied to the transaction.

1. Uniform Cut-Off Timings Established by SEBI:
• Equity, Debt, and Hybrid Schemes:
  - Cut-Off Time: 3:00 PM (Indian Standard Time).
  - Rule of Realization: Under current SEBI regulations, same-day NAV is granted ONLY if the application is submitted before 3:00 PM AND the investor's funds are realized in the mutual fund scheme's bank account before 3:00 PM.
  - Payment Gateway Implications: UPI and net banking transactions generally clear instantly, securing same-day NAV. NEFT or RTGS transfers clearing after 3:00 PM will receive the next business day's NAV.

• Liquid and Overnight Schemes:
  - Cut-Off Time: 1:30 PM (IST).
  - NAV Applied: If funds and application are received before 1:30 PM, the investor receives the NAV of the **day immediately preceding the transaction** (historic day's NAV), allowing idle corporate cash to start earning overnight interest immediately.
  - If submitted after 1:30 PM, the same day's closing NAV is applied.

2. Redemptions (Selling Units):
• The cut-off time across all schemes for redemptions is 3:00 PM. Applications placed before 3:00 PM are processed at that day's closing NAV.
• Settlement Cycles: Equity mutual fund redemptions typically credit investor bank accounts on a T+2 business day schedule; Liquid funds settle on a T+1 business day basis."""

    elif term == "ter_regulation52":
        return """Regulatory Anatomy: Total Expense Ratio (TER) Under SEBI Regulation 52

The Total Expense Ratio (TER) represents the annual percentage fee deducted daily from a mutual fund's Net Asset Value (NAV) to cover investment management, administration, custodial, audit, and distribution expenses.

1. Statutory TER Caps Under Regulation 52:
SEBI legally caps the maximum TER an AMC can charge based on the scheme's Asset Under Management (AUM) slabs:
• First ₹500 Crore of AUM: Maximum TER of 2.25% (Equity) / 2.00% (Debt)
• Next ₹250 Crore: Maximum 2.00% (Equity) / 1.75% (Debt)
• Next ₹1,250 Crore: Maximum 1.75% (Equity) / 1.50% (Debt)
• Next ₹3,000 Crore: Maximum 1.60% (Equity) / 1.35% (Debt)
• Next ₹5,000 Crore: Maximum 1.50% (Equity) / 1.25% (Debt)
• Next ₹40,000 Crore: TER reduces by 0.05% for every ₹5,000 Crore increase in AUM
• Above ₹50,000 Crore: Maximum TER capped at 1.05% (Equity) / 0.80% (Debt)

2. B-30 Incentive Mechanism:
AMCs are permitted to charge up to 30 basis points (0.30%) additional TER if new inflows from B-30 cities (cities beyond the Top 30 financial hubs) exceed specific thresholds, incentivizing mutual fund penetration into semi-urban and rural India.

3. Direct vs Regular TER Gap:
Under SEBI mandates, the Direct plan of every mutual fund must have a lower TER than the Regular plan by exactly the amount paid as distributor commission. In equity funds, this spread typically ranges from 0.70% to 1.30% annually, which compounds directly into higher returns for direct unitholders."""

    elif term == "portfolio_turnover_ratio":
        return """Investment Metric: Portfolio Turnover Ratio (PTR) in Mutual Funds

The Portfolio Turnover Ratio (PTR) measures how frequently a fund manager buys and sells securities within the mutual fund's portfolio over a rolling 12-month period.

1. Mathematical Formulation:
    PTR = Min(Total Equity Purchases, Total Equity Sales) / Average Monthly Portfolio AUM

For instance, a PTR of 0.30 (or 30%) indicates that roughly one-third of the portfolio's holdings were replaced or rebalanced over the past year. A PTR of 1.50 (150%) implies the fund manager churned through the entire value of the portfolio one and a half times.

2. Strategic Interpretation:
• Low PTR (< 0.30): Indicates a disciplined, high-conviction buy-and-hold value investing philosophy (exemplified by Parag Parikh Flexi Cap or HDFC Flexi Cap). Lower turnover minimizes brokerage charges, STT, and transaction friction.
• High PTR (> 1.00): Reflects an aggressive, quantitative, or momentum-based sectoral rotation strategy (exemplified by Quant Mutual Fund). While transaction costs are higher, the strategy aims to generate alpha by capturing rapid market trends.

3. Takeaway for Retail Investors:
A high PTR is not inherently bad if the net-of-cost alpha consistently outperforms the benchmark. However, during sideways or choppy markets, funds with high turnover often bleed returns due to trading friction."""

    else:
        return """Legal Documentation: SID, KIM, and the Monthly Fund Factsheet

Every mutual fund scheme in India is governed by three primary regulatory disclosure documents mandated by SEBI:

1. Scheme Information Document (SID):
The SID is the comprehensive legal constitution of a mutual fund scheme. It details:
• Statutory investment objectives and asset allocation ranges (e.g., 65%–100% equity, 0%–35% debt).
• Permissible derivative usage and overseas securities limits.
• Benchmark selection and risk profile.
• Fund manager credentials, track record, and educational background.
• Applicable fee structures, maximum TER, and exit load schedules.

2. Key Information Memorandum (KIM):
The KIM is an abridged, investor-friendly summary of the SID. By law, every physical or digital application form for a mutual fund must be accompanied by the KIM so investors can understand scheme features, minimum investment amounts, and risk factors without reading a 100-page prospectus.

3. Monthly Fund Factsheet:
Published by every AMC within 10 days of each month's close, the factsheet provides transparent, real-time accountability:
• Complete portfolio disclosure: Every single stock, bond, and cash equivalent held on the last trading day of the month with exact percentage weights.
• Key Quantitative Ratios: Standard Deviation, Sharpe Ratio, Beta, Treynor Ratio, and Portfolio Turnover.
• Trailing Performance vs. Benchmark across 1-year, 3-year, 5-year, and since-inception timeframes."""


# =========================================================================== #
# PILLAR 2: SEBI / AMFI Regulatory Knowledge (Target: 88%)
# =========================================================================== #
def gen_sebi_amfi_regulations(r):
    topic = r.choice([
        "risk_o_meter", "one_scheme_per_category", "market_cap_reclassification",
        "scores_grievance", "amfi_code_ethics"
    ])
    
    if topic == "risk_o_meter":
        return """SEBI Regulatory Framework: The Dynamic 6-Level Risk-o-meter

The Risk-o-meter is a standardized, visual risk depiction mandated by SEBI to inform Indian investors of the exact level of risk associated with their principal investment.

1. The Six Standardized Risk Tiers:
Under SEBI guidelines, every mutual fund scheme must be assigned to one of six granular risk tiers:
1. Low Risk
2. Low to Moderate Risk
3. Moderate Risk
4. Moderately High Risk
5. High Risk
6. Very High Risk

2. Monthly Dynamic Evaluation:
Historically, a scheme's Risk-o-meter was static. Under the modernized SEBI circular:
• Quantitative Calculation: AMCs must evaluate portfolio risk dynamically at the end of every single calendar month.
• Liquidity, Volatility, and Credit Metrics: For debt securities, risk is calculated based on credit rating (AAA vs AA), duration, and liquidity. For equity securities, risk is computed based on market capitalization, volatility (standard deviation), and liquidity impact cost.
• Monthly Updates: If a fund manager purchases higher-risk mid-cap stocks or lowers credit quality, the Risk-o-meter needle automatically moves upward on the scheme's factsheet and AMC portal.

3. Mandatory Disclosure:
Any change in the Risk-o-meter level must be communicated to all existing unitholders via email/SMS and published in at least two national daily newspapers, ensuring full investor transparency."""

    elif topic == "one_scheme_per_category":
        return """SEBI Rationalization Directive: The 'One Scheme Per Category' Rule

In October 2017, SEBI issued a landmark circular on the 'Categorization and Rationalization of Mutual Fund Schemes', transforming the Indian mutual fund industry.

1. The Pre-2017 Problem:
Prior to this reform, Indian fund houses launched dozens of confusing, overlapping schemes with ambiguous names (e.g., 'Advantage Fund', 'Growth Fund', 'Opportunities Fund', 'Mega Cap Fund'). Investors could not distinguish which fund did what, and AMCs used duplicate funds to game past performance leaderboards.

2. The Strict SEBI Mandate:
SEBI established 36 clearly defined mutual fund categories grouped into five broad groups: Equity (10 categories), Debt (16 categories), Hybrid (6 categories), Solution-Oriented (2 categories), and Other Schemes (2 categories).

The Universal Core Rule:
An Asset Management Company (AMC) is legally permitted to operate only **ONE scheme per category**. For example:
• An AMC can have only ONE Large Cap Fund.
• An AMC can have only ONE Flexi Cap Fund.
• An AMC can have only ONE Mid Cap Fund.

3. Permitted Exceptions:
The only exceptions to this rule are:
• Index Funds and Exchange Traded Funds (ETFs) replicating different distinct market indices (e.g., an AMC can have both a Nifty 50 Index Fund and a Nifty Midcap 150 Index Fund).
• Sectoral and Thematic Funds focused on completely distinct industries (e.g., a Banking & Financial Services Fund vs. a Technology Sector Fund)."""

    elif topic == "market_cap_reclassification":
        return """SEBI Uniform Market Capitalization Definition: The Semi-Annual Reclassification

To ensure absolute consistency across all mutual fund schemes, SEBI established a rigid, objective definition of market capitalization tiers based on the National Stock Exchange (NSE) and Bombay Stock Exchange (BSE) rankings.

1. The Three Universal Market Cap Slabs:
• Large Cap Companies: The top 100 companies in India by full market capitalization (Rank 1 to 100). Examples: Reliance Industries, TCS, HDFC Bank, Infosys, Bharti Airtel.
• Mid Cap Companies: The 101st to the 250th company by market capitalization (Rank 101 to 250). Examples: Cummins India, Federal Bank, Ashok Leyland, Polycab.
• Small Cap Companies: The 251st company onwards (Rank 251 and below).

2. The Semi-Annual AMFI Reclassification Cycle:
The Association of Mutual Funds in India (AMFI) compiles and publishes the official, binding market capitalization list twice every year:
• December Data: Published in January, valid from February to July.
• June Data: Published in July, valid from August to January.

3. Rebalancing Grace Period:
When a high-performing mid-cap stock rises into the top 100 (promoted to large-cap), or a large-cap stock falls into the 101-250 rank (demoted to mid-cap), SEBI grants fund managers a strict **one-month grace period** to rebalance their portfolio to ensure compliance with category mandates without disrupting market prices."""

    else:
        return """Investor Rights & Redressal: SCORES 2.0 and the SMART ODR Portal

SEBI has instituted one of the most robust and transparent online grievance redressal ecosystems in global capital markets to protect Indian mutual fund unitholders.

1. SEBI Complaints Redress System (SCORES 2.0):
If an investor faces issues with an AMC, registrar (CAMS/KFintech), or distributor—such as unauthorized deductions, failure to credit redemption proceeds, delayed unit allocation, or non-receipt of account statements:
• Step 1: File an official complaint directly with the AMC's designated Investor Relations Officer.
• Step 2 (SCORES Escalation): If the AMC does not resolve the complaint within 21 calendar days, the investor can escalate the complaint directly onto SEBI's centralized SCORES portal (scores.sebi.gov.in).
• Automatic Penalties: SEBI tracks resolution timelines; failure by an AMC to resolve a verified grievance within statutory deadlines triggers regulatory scrutiny and financial penalties.

2. SMART Online Dispute Resolution (ODR) Portal:
Introduced in 2023, the SMART ODR platform provides independent, digital conciliation and arbitration for unitholders. Investors can initiate online conciliation with zero legal fees for claims up to specified limits, ensuring retail investors possess equal bargaining power against large financial institutions."""


# =========================================================================== #
# PILLAR 3: Step-by-Step Numerical Advisory Explanations (Target: 82%)
# =========================================================================== #
def gen_step_by_step_math_explanations(r):
    sip = r.choice([5000, 7500, 10000, 15000, 20000, 25000, 30000, 50000])
    yrs = r.choice([5, 10, 15, 20])
    ann = r.choice([10.0, 11.0, 12.0, 13.0, 14.0])
    n = yrs * 12
    i = ann / 100 / 12
    fv = R(sip * (((1 + i) ** n - 1) / i) * (1 + i))
    invested = sip * n
    gain = fv - invested
    name = r.choice(NAMES)
    
    return f"""Quantitative Advisory Breakdown: Step-by-Step SIP Compounding Analysis

An investor, {name}, is evaluating a monthly SIP of ₹{money(sip)} for {yrs} years. Assuming an average equity market compounding rate of {ann:.1f}% per annum, here is the complete mathematical derivation of principal accumulation versus capital compounding:

Step 1: Conversion to Monthly Parameters
• Monthly Instalment (P) = ₹{money(sip)}
• Annual Return Assumption (R) = {ann:.1f}%
• Monthly Rate (i) = R / 100 / 12 = {ann:.1f} / 1200 = {i:.6f} per month
• Total Number of Instalments (n) = {yrs} years x 12 months = {n} instalments

Step 2: The Future Value of Annuity-Due Equation
Because mutual fund SIP instalments are invested at the start of each monthly cycle, we apply the standard compounding formula:
    FV = P x [ ((1 + i)^n - 1) / i ] x (1 + i)

Step 3: Intermediate Variable Substitution
• Compounding Factor: (1 + i)^n = (1 + {i:.6f})^{n} = {(1+i)**n:.4f}
• Geometric Series Sum: ((1 + i)^n - 1) / i = ({(1+i)**n:.4f} - 1) / {i:.6f} = {((1+i)**n - 1)/i:.4f}
• Start-of-Period Multiplier: (1 + i) = {1+i:.6f}

Step 4: Final Corpus Calculation
    FV = ₹{money(sip)} x {((1+i)**n - 1)/i:.4f} x {1+i:.6f} = ₹{money(fv)} ({lakh(fv)})

Step 5: Capital Breakdown & Growth Share
• Total Out-of-Pocket Contribution = ₹{money(sip)} x {n} months = ₹{money(invested)} ({lakh(invested)})
• Wealth Generated via Compounding = ₹{money(fv)} - ₹{money(invested)} = ₹{money(gain)} ({lakh(gain)})
• Compounding Multiplier: The final corpus is {fv/invested:.2f}x the money contributed.
• Profit Percentage: Capital gains account for {(gain/fv)*100:.1f}% of the total accumulated wealth.

This step-by-step math demonstrates that in mutual fund investing, the initial years feel slow because contributions dominate, but in the final years, compounding does over 60% of the heavy lifting."""


# =========================================================================== #
# PILLAR 4: Fiduciary Advisory Tone & Strategic Dialogues (Target: 93%)
# =========================================================================== #
def gen_fiduciary_advisory_dialogue(r):
    name = r.choice(NAMES)
    city = r.choice(CITIES)
    age = r.choice([25, 29, 34, 40, 47, 52])
    salary = r.choice([75000, 100000, 150000, 200000, 300000])
    sip = r.choice([10000, 20000, 30000, 45000, 60000])
    horizon = r.choice([5, 8, 12, 15, 20])
    
    return f"""User: I am {age}, living in {city}, earning ₹{salary:,}/month. I can save ₹{sip:,} monthly. A bank manager told me to put it all into an NFO (New Fund Offer) and a sectoral EV fund. What is your honest advice?
Assistant: As a fiduciary financial advisor, my responsibility is to protect your long-term wealth, {name}. I strongly advise **against** investing your entire ₹{sip:,} monthly savings into New Fund Offers (NFOs) or sectoral EV funds. 

Here is an objective, conflict-free breakdown of why that recommendation is flawed, followed by a prudent alternative:

1. The Pitfalls of NFOs and Sectoral Funds:
• NFOs Offer No Special Bargain: Unlike an IPO in direct equity (where a company might list at a discount to intrinsic value), a mutual fund NFO at ₹10 NAV has zero historical track record. You are essentially handing money to a fund manager with an untested portfolio strategy.
• Sector Concentration Risk: Sectoral themes (like EV, Defense, or Pharma) are high-risk cyclical plays. If regulatory subsidies change or raw material costs spike, the EV sector can underperform the broader market for 4 to 6 consecutive years. A retail investor should never place their core wealth in a narrow thematic bet.
• Hidden Commissions: Bank relationship managers frequently push NFOs and high-margin funds because AMCs offer lucrative upfront distributor commissions during campaign launches.

2. The Evidence-Based Fiduciary Strategy for Your {horizon}-Year Horizon:
At age {age} with a {horizon}-year runway, your wealth engine should be built on diversified, multi-cap market exposure:

• 50% in a Flexi Cap Direct Fund (₹{int(sip*0.5):,}/month):
  Gives your fund manager the flexibility to invest across Large, Mid, and Small caps based on macroeconomic valuation cycles.
• 30% in a Nifty 50 Index Direct Fund (₹{int(sip*0.3):,}/month):
  Captures India's top 50 bluechip corporate giants at an ultra-low expense ratio (~0.10%), providing robust downside stability.
• 20% in a Mid Cap Direct Fund (₹{int(sip*0.2):,}/month):
  Powers long-term capital appreciation by investing in fast-growing mid-sized market leaders.

3. Four Golden Fiduciary Rules:
1. Choose **Direct - Growth** plans exclusively to save ~1% annually in broker commissions.
2. Maintain a standalone term life policy (15x annual income) and family health coverage before investing in equity.
3. Keep 6 months of mandatory living expenses (₹{salary*3:,}) in an emergency liquid fund.
4. Let your SIP compound uninterrupted; review the portfolio once a year, not every week.

Would you like me to calculate your projected compounding corpus over your {horizon}-year horizon?"""


GENERATORS = [
    (gen_indian_finance_terms, 0.30),
    (gen_sebi_amfi_regulations, 0.25),
    (gen_step_by_step_math_explanations, 0.25),
    (gen_fiduciary_advisory_dialogue, 0.20),
]


def main():
    parser = argparse.ArgumentParser(description="Generate specialized 4-pillars training corpus")
    parser.add_argument("--target_mib", type=float, default=50.0, help="Target file size in MiB (~12-15M tokens)")
    parser.add_argument("--seed", type=int, default=777)
    parser.add_argument("--out", default=str(OUT_JSONL))
    args = parser.parse_args()

    r = random.Random(args.seed)
    fns = [f for f, _ in GENERATORS]
    weights = [w for _, w in GENERATORS]
    target_bytes = args.target_mib * MIB

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    written = 0
    n = 0
    counts = {}

    print(f"Generating ~{args.target_mib:.1f} MiB of 4-Pillars Mastery Data...")
    with open(out_path, "w", encoding="utf-8") as f:
        while written < target_bytes:
            fn = r.choices(fns, weights=weights, k=1)[0]
            text = fn(r).strip()
            line = json.dumps({"text": text, "source": "four_pillars_mastery", "domain": "advisory_india"}, ensure_ascii=False) + "\n"
            f.write(line)
            written += len(line.encode("utf-8"))
            n += 1
            counts[fn.__name__] = counts.get(fn.__name__, 0) + 1
            if n % 5000 == 0:
                print(f"  {n:,} passages written | {written / MIB:.1f}/{args.target_mib:.1f} MiB", flush=True)

    print(f"\n[DONE] Wrote {n:,} 4-Pillars Mastery passages ({written / MIB:.1f} MiB) to {out_path}")
    for k, v in counts.items():
        print(f"  - {k:35}: {v:,} ({v/n*100:.1f}%)")


if __name__ == "__main__":
    main()
